- name: Placing .gitconfig dotfile
  copy:
    src: files/cfg/home/.gitconfig
    dest: "{{ my_home }}/.gitconfig"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing .gitignore dotfile
  copy:
    src: files/cfg/home/.gitignore
    dest: "{{ my_home }}/.gitignore"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing Ncspot CFG
  copy:
    src: files/cfg/home/snap/ncspot/current/.config/ncspot/config.toml
    dest: "{{ my_home }}/snap/ncspot/current/.config/ncspot/config.toml"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing .sbuildrc
  copy:
    src: files/cfg/home/.sbuildrc
    dest: "{{ my_home }}/.sbuildrc"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing .mk-sbuild.rc
  copy:
    src: files/cfg/home/.mk-sbuild.rc
    dest: "{{ my_home }}/.mk-sbuild.rc"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing .quiltrc
  copy:
    src: files/cfg/home/.quiltrc
    dest: "{{ my_home }}/.quiltrc"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing .vimrc
  copy:
    src: files/cfg/home/.vimrc
    dest: "{{ my_home }}/.vimrc"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing brave profile-sync-daemon file
  copy:
    src: files/cfg/usr/share/psd/browsers/brave-browser
    dest: "/usr/share/psd/browsers/brave-browser"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0644

- name: Placing .editorconfig default file
  copy:
    src: files/cfg/home/.config/editorconfig/.editorconfig
    dest: "{{ my_home }}/.config/editorconfig/.editorconfig"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing uncrustify.cfg
  copy:
    src: files/cfg/home/.config/uncrustify/uncrustify.cfg
    dest: "{{ my_home }}/.config/uncrustify/uncrustify.cfg"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing .hidden file (Clean home dir)
  copy:
    src: files/cfg/home/.hidden
    dest: "{{ my_home }}/.hidden"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing gh-create-repo.sh
  copy:
    src: files/cfg/usr/local/bin/github-init-main.sh
    dest: "/usr/local/bin/github-init-main.sh"
    owner: root
    group: root
    mode: 0755

- name: Placing .screenlayout/desktop.sh
  copy:
    src: files/cfg/home/.screenlayout/desktop.sh
    dest: "{{ my_home }}/.screenlayout/desktop.sh"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700
