- name: Installing Fish Shell
  apt:
    pkg:
      - git
      - fish
      - fonts-powerline
      - powerline
    state: present
  register: install_fish

- name: Change current user shell
  user:
        name: "{{ my_username }}"
        shell: /usr/bin/fish
  become: yes

- name: Get latest release version of Starship.rs from GitHub
  github_release:
    user: starship
    repo: starship
    action: latest_release
  register: starship_release
- name: Download & Extract Starship.rs Tgz
  unarchive:
    src: "https://github.com/starship/starship/releases/download/{{ starship_release.tag }}/starship-x86_64-unknown-linux-gnu.tar.gz"
    dest: /usr/local/bin
    # Ditch the containing folder on extraction
    extra_opts: [--strip-components=1]
    remote_src: yes
#   when: starship_release.changed

- name: Placing Starship config for prompt
  copy:
    src: files/cfg/home/.config/starship.toml
    dest: "{{ my_home }}/.config/starship.toml"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing config.fish dotfile
  copy:
    src: files/cfg/home/.config/fish/config.fish
    dest: "{{ my_home }}/.config/fish/config.fish"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing env.fish file
  copy:
    src: files/cfg/home/.config/fish/conf.d/env.fish
    dest: "{{ my_home }}/.config/fish/conf.d/env.fish"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing alacritty.fish file
  copy:
    src: files/cfg/home/.config/fish/conf.d/alacritty.fish
    dest: "{{ my_home }}/.config/fish/conf.d/alacritty.fish"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

- name: Placing alacritty.yml file
  copy:
    src: files/cfg/home/.config/alacritty/alacritty.yml
    dest: "{{ my_home }}/.config/alacritty/alacritty.yml"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

# - name: Placing aws-cli.zsh CFG
#   copy:
#         src: files/cfg/home/.oh-my-zsh/custom/aws-cli.zsh
#         dest: "{{ my_home }}/.oh-my-zsh/custom/aws-cli.zsh"
#         owner: "{{ my_username }}"
#         group: "{{ my_username }}"