- name: Placing Wallpaper
  copy:
    src: files/cfg/home/.local/share/backgrounds/nord.jpg
    dest: "{{ my_home }}/.local/share/backgrounds/nord.jpg"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0700

# WHen updating to new look, must delete `~/.Xresources-regolith` first. Careful if any other customizastions end up in there.
# Will not show up until reboot or you run `regolith-look refresh`
- name: Set Regolith-look to Nord
  become: yes
  become_user: "{{ my_username }}"
  command: regolith-look set nord && regolith-look refresh
  args:
    creates: "{{ my_home }}/.Xresources-regolith"

# Needs to be run after the refresh
- name: Setting Wallpaper
  become: true
  become_user: "{{ my_username }}"
  dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file://{{ my_home }}/.local/share/backgrounds/nord.jpg'"
      state: present