
# WHen updating to new look, must delete `~/.Xresources-regolith` first. Careful if any other customizastions end up in there.
# Will not show up until reboot or you run `regolith-look refresh`
- name: Set Regolith-look to Nord
  become: yes
  become_user: "{{ my_username }}"
  command: regolith-look set nord && regolith-look refresh
  args:
    creates: "{{ my_home }}/.Xresources-regolith"

# Using a custom config due to terminal/Nvidia glitches.
- name: Custom Picom Config (Nvidia Glitch)
  tags:
  - nvidia-compton-fix
  copy:
    src: files/cfg/home/.config/regolith/compton/config
    dest: "{{ my_home }}/.config/regolith/compton/config"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0644

- name: Adding Custom Xresource overrides
  copy:
    src: files/cfg/home/.config/regolith/Xresources
    dest: "{{ my_home }}/.config/regolith/Xresources"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0644