- name: Add Docker's public PGP key to the APT keyring
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: "https://download.docker.com/linux/ubuntu/gpg"

# Hard code release so that it will work on 20.04
# When Docker supports officially - need to change
- name: Configure Docker's upstream APT STABLE Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    update_cache: true

- name: Remove Old Docker APT Packages (Ubuntu/Debian)
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install Docker CE
  apt:
    pkg:
      # Docker main
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present

- name: Add User to docker group
  user:
    name: "{{ my_username }}"
    groups: docker
    append: yes