- name: Installing Docker Dependencies - APT
  apt:
    pkg:
        # Docker Dependencies
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present