- name: Add Launchpad PPAs
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - ppa:peek-developers/stable
    - ppa:bashfulrobot/pop-theme

- name: Add Canonical Partners PPA
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner
    state: present

- name: Add NordVPN APT signing Keys
  apt_key:
    url: https://repo.nordvpn.com/gpg/nordvpn_public.asc
    state: present
- name: Add NordVPN PPA
  apt_repository:
    repo: deb https://repo.nordvpn.com/deb/nordvpn/debian stable main
    state: present

# - name: Add Brave APT signing Keys
#   apt_key:
#     url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
#     state: present
# - name: Add Brave Browser PPA
#   apt_repository:
#     repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
#     state: present

- name: Add Tailscale APT signing Keys
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/focal.gpg
    state: present
- name: Add Tailscale PPA
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu focal main
    state: present